### ISSUE TITLE
请问CPM的小模型打算放出来吗？

### ISSUE THREAD

**Issue by realTaki** [TsinghuaAI/CPM#6]
我看到现在只放了最大的模型，100M和300M的小模型都没有公开？

另外想问问社区里面有没有其他大佬训练过100M和300M模型，可以分享一下吗？

**Comment by zzy14** [comment]
Hi，我们开源了蒸馏版的100M模型，可以参考https://github.com/TsinghuaAI/CPM-1-Generate的README。

**Comment by yixuan-qiao** [comment]
> Hi，我们开源了蒸馏版的100M模型，可以参考[https://github.com/TsinghuaAI/CPM-1-Generate的README。](https://github.com/TsinghuaAI/CPM-1-Generate%E7%9A%84README%E3%80%82)

感谢分享！
CPM-1 系列的下载地址，包括蒸馏版本的下载地址打不开，能否提供一个新的下载地址，非常感谢！

**Comment by zzy14** [comment]
@yixuan-qiao 有一个transformers的版本 https://huggingface.co/mymusise/CPM-Generate-distill
